sports_dict = {
    "BK3": "3X3 농구",
    "RUG": "7인제 럭비",
    "GAR": "기계체조",
    "DIV": "다이빙",
    "SHO": "사격",
    "CRD": "사이클 도로",
    "MTB": "사이클 산악 자전거",
    "SRF": "서핑",
    "SWM": "수영",
    "SKB": "스케이트보드",
    "EQU": "승마",
    "BSB": "야구/소프트볼",
    "ARC": "양궁",
    "WLF": "역도",
    "JUD": "유도",
    "ROW": "조정",
    "CSL": "카누 슬라럼",
    "TTE": "탁구",
    "TKW": "태권도",
    "TRI": "트라이애슬론",
    "FEN": "펜싱",
}

countries_dict = {
    "ROC": "ROC",
    "GHA": "가나",
    "GAB": "가봉",
    "GUY": "가이아나",
    "GAM": "감비아",
    "GUA": "과테말라",
    "GUM": "괌",
    "GRN": "그레나다",
    "GRE": "그리스",
    "GUI": "기니",
    "GBS": "기니비사우",
    "NAM": "나미비아",
    "NRU": "나우루",
    "NGR": "나이지리아",
    "EOR": "난민 올림픽 대표팀",
    "SSD": "남수단",
    "RSA": "남아프리카공화국",
    "NED": "네덜란드",
    "NEP": "네팔",
    "NOR": "노르웨이",
    "NZL": "뉴질랜드",
    "NIG": "니제르",
    "NCA": "니카라과",
    "KOR": "대한민국",
    "DEN": "덴마크",
    "DMA": "도미니카",
    "DOM": "도미니카공화국",
    "GER": "독일",
    "TLS": "동티모르",
    "LAO": "라오스",
    "LBR": "라이베리아",
    "LAT": "라트비아",
    "LBN": "레바논",
    "LES": "레소토",
    "ROU": "루마니아",
    "LUX": "룩셈부르크",
    "RWA": "르완다",
    "LBA": "리비아",
    "LTU": "리투아니아",
    "LIE": "리히텐슈타인",
    "MAD": "마다가스카르",
    "MHL": "마셜 제도",
    "MAW": "말라위",
    "MAS": "말레이시아",
    "MLI": "말리",
    "MEX": "멕시코",
    "MON": "모나코",
    "MAR": "모로코",
    "MRI": "모리셔스",
    "MTN": "모리타니",
    "MOZ": "모잠비크",
    "MNE": "몬테네그로",
    "MDA": "몰도바",
    "MDV": "몰디브",
    "MLT": "몰타",
    "MGL": "몽골",
    "USA": "미국",
    "MYA": "미얀마",
    "FSM": "미크로네시아",
    "VAN": "바누아투",
    "BRN": "바레인",
    "BAR": "바베이도스",
    "BAH": "바하마",
    "BAN": "방글라데시",
    "BER": "버뮤다",
    "ISV": "버진아일랜드(미국령)",
    "BEN": "베냉",
    "VEN": "베네수엘라",
    "VIE": "베트남",
    "BEL": "벨기에",
    "BLR": "벨라루스",
    "BIZ": "벨리즈",
    "BIH": "보스니아헤르체고비나",
    "BOT": "보츠와나",
    "BOL": "볼리비아",
    "BDI": "부룬디",
    "BUR": "부르키나파소",
    "BHU": "부탄",
    "MKD": "북마케도니아공화국",
    "BUL": "불가리아",
    "BRA": "브라질",
    "BRU": "브루나이",
    "SAM": "사모아",
    "KSA": "사우디 아라비아",
    "SMR": "산마리노",
    "STP": "상투메프린시페",
    "SEN": "세네갈",
    "SRB": "세르비아",
    "SEY": "세이셸",
    "LCA": "세인트루시아",
    "VIN": "세인트빈센트그레나딘",
    "SKN": "세인트키츠네비스",
    "SOM": "소말리아",
    "SOL": "솔로몬 제도",
    "SUD": "수단",
    "SUR": "수리남",
    "SRI": "스리랑카",
    "SWE": "스웨덴",
    "SUI": "스위스",
    "ESP": "스페인",
    "SVK": "슬로바키아",
    "SLO": "슬로베니아",
    "SYR": "시리아",
    "SLE": "시에라리온",
    "SGP": "싱가포르",
    "UAE": "아랍에미리트",
    "ARU": "아루바",
    "ARM": "아르메니아",
    "ARG": "아르헨티나",
    "ASA": "아메리칸사모아",
    "ISL": "아이슬란드",
    "HAI": "아이티",
    "IRL": "아일랜드",
    "AZE": "아제르바이잔",
    "AFG": "아프가니스탄",
    "AND": "안도라",
    "ALB": "알바니아",
    "ALG": "알제리",
    "ANG": "앙골라",
    "ANT": "앤티가바부다",
    "ERI": "에리트레아",
    "SWZ": "에스와티니",
    "EST": "에스토니아",
    "ECU": "에콰도르",
    "ETH": "에티오피아",
    "ESA": "엘살바도르",
    "GBR": "영국",
    "IVB": "영국령 버진아일랜드",
    "YEM": "예멘",
    "OMA": "오만",
    "AUS": "오스트레일리아",
    "AUT": "오스트리아",
    "HON": "온두라스",
    "JOR": "요르단",
    "UGA": "우간다",
    "URU": "우루과이",
    "UZB": "우즈베키스탄",
    "UKR": "우크라이나",
    "IRQ": "이라크",
    "IRI": "이란",
    "ISR": "이스라엘",
    "EGY": "이집트",
    "ITA": "이탈리아",
    "IND": "인도",
    "INA": "인도네시아",
    "JPN": "일본",
    "JAM": "자메이카",
    "ZAM": "잠비아",
    "GEQ": "적도 기니",
    "GEO": "조지아",
    "CHN": "중국",
    "CAF": "중앙아프리카공화국",
    "DJI": "지부티",
    "ZIM": "짐바브웨",
    "CHA": "차드",
    "TPE": "차이니스 타이베이",
    "CZE": "체코",
    "CHI": "칠레",
    "CMR": "카메룬",
    "CPV": "카보베르데",
    "KAZ": "카자흐스탄",
    "QAT": "카타르",
    "CAM": "캄보디아",
    "CAN": "캐나다",
    "KEN": "케냐",
    "CAY": "케이맨 제도",
    "COM": "코모로",
    "KOS": "코소보",
    "CRC": "코스타리카",
    "CIV": "코트디부아르",
    "COL": "콜롬비아",
    "CGO": "콩고 공화국",
    "COD": "콩고 민주 공화국",
    "CUB": "쿠바",
    "KUW": "쿠웨이트",
    "COK": "쿡 아일랜드/쿡 제도",
    "CRO": "크로아티아",
    "KGZ": "키르기스스탄",
    "KIR": "키리바시",
    "CYP": "키프로스",
    "TJK": "타지키스탄",
    "TAN": "탄자니아",
    "THA": "태국",
    "TUR": "터키",
    "TOG": "토고",
    "TGA": "통가",
    "TKM": "투르크메니스탄",
    "TUV": "투발루",
    "TUN": "튀니지",
    "TTO": "트리니다드토바고",
    "PAN": "파나마",
    "PAR": "파라과이",
    "PAK": "파키스탄",
    "PNG": "파푸아뉴기니",
    "PLW": "팔라우",
    "PLE": "팔레스타인",
    "PER": "페루",
    "POR": "포르투갈",
    "POL": "폴란드",
    "PUR": "푸에르토리코",
    "FRA": "프랑스",
    "FIJ": "피지",
    "FIN": "핀란드",
    "PHI": "필리핀",
    "HUN": "헝가리",
    "HKG": "홍콩",
}


# from crawl_olympic import parsing_bs
# url = 'https://olympics.com/tokyo-2020/olympic-games/ko/results/all-sports/medalists.htm'
# soup = parsing_bs(url)
# li_list = soup.select('li.dropdown-item')
# translated_dict = {}
# for sport in li_list[21:42]:
#     en_sports = sport.attrs['name']
#     kor_sports = sport.text.strip()
#     translated_dict[en_sports] = kor_sports
# translated_countries_dict = {}
#
# for country in li_list[388:-5]:
#     noc = country.attrs['name']
#     kor_country = country.select_one('span').text
#     translated_countries_dict[noc] = kor_country
